### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [ejvkamp/prj-rev-bwfs-dasmoto#2]
Rather than having to set the font-family in so many selectors we can set the pages default font in one place using inheritance:
html { font-family: Helvetica; }
Now all elements will default to this font.

https://github.com/ejvkamp/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L2

**Comment by ejvkamp** [comment]
Thanks for the tip and good to know. I wasn't sure as the design spec only referred to certain sections having a font-family.
