### ISSUE TITLE
header tags bold

### ISSUE THREAD

**Issue by rimmesbe** [ejvkamp/prj-rev-bwfs-dasmoto#3]
Header tags (h1, h2, h3...) default to bold, so no need to add it.

https://github.com/ejvkamp/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L13

**Comment by ejvkamp** [comment]
Thank you for the feedbak. It was called out in the spec so I just took it verbatim but will remember there's no need to include going forward.
