### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [ejvkamp/prj-rev-bwfs-dasmoto#5]
Grade: Exceeds expectations

Summary: Great job on this project, the site looks good. You used a lot of good techniques and kept your code very organized and efficient. Take a look at the issues I created for a couple minor best practice tweaks, but overall not much to critique here. Well done, you are ready for the next units.

**Comment by ejvkamp** [comment]
Thank you very much and I appreciate your thoughtful feedback.
